{% set name = "lz4" %}
{% set version = "2.0.1" %}
{% set sha256 = "ad2829319cf151720724399cb5a14f6fb90abe5edfe2fabc1233e765d3e718b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - toolchain
    - python
    - pip
    - pytest-runner
    - setuptools_scm
    - pkgconfig
    - lz4-c 1.8.1
  run:
    - python
    - lz4-c 1.8.1

test:
  imports:
    - lz4

about:
  home: https://github.com/python-lz4/python-lz4
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "LZ4 Bindings for Python"

  doc_url: http://python-lz4.readthedocs.io/en/stable/
  dev_url: https://github.com/python-lz4/python-lz4

extra:
  recipe-maintainers:
    - jakirkham
