{% set name = "lz4" %}
{% set version = "2.1.10" %}
{% set sha256 = "db4ac5a9b54d6d6b5bb0d6f9b77790f1460e2aeb37cd8ec76c96fe78aaf4a2a8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and vc<14]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - pytest-runner
    - setuptools_scm
    - pkgconfig
    - lz4-c
  run:
    - python
    - lz4-c

test:
  imports:
    - lz4

about:
  home: https://github.com/python-lz4/python-lz4
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "LZ4 Bindings for Python"

  doc_url: http://python-lz4.readthedocs.io/en/stable/
  dev_url: https://github.com/python-lz4/python-lz4

extra:
  recipe-maintainers:
    - jakirkham
