{% set name = "lz4" %}
{% set version = "4.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01fe674ef2889dbb9899d8a67361e0c4a2c833af5aeb37dd505727cf5d2a131e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
    - setuptools_scm
    - pkgconfig
    - lz4-c
  run:
    - python
    - lz4-c

test:
  imports:
    - lz4

about:
  home: https://github.com/python-lz4/python-lz4
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: LZ4 Bindings for Python

  doc_url: http://python-lz4.readthedocs.io/en/stable/
  dev_url: https://github.com/python-lz4/python-lz4

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
