schema_version: 1

context:
  name: lz4
  version: 4.4.5

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5f0b9e53c1e82e88c10d7c180069363980136b9d7a8306c4dca4f760d60c39f0

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - pytest-runner
    - setuptools
    - setuptools_scm
    - pkgconfig
    - lz4-c
  run:
    - python
    - lz4-c

tests:
  - python:
      imports:
        - lz4

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: LZ4 Bindings for Python
  homepage: https://github.com/python-lz4/python-lz4
  repository: https://github.com/python-lz4/python-lz4
  documentation: http://python-lz4.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - jakirkham
    - xhochy
