appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: KjxPRiHP6+Xgj/ptyZP7gTM2QYcUPZfUAljeKiLWRUlzJ3EmGvkCHpl2zslT/tWK5ghNxbWdPw7mWSet+YQVSP7Jl7//MV2c+5WVcwR/OxLH2jXMD8uT2w4SOcFDWKBq3Rr2r9/YV699zTvspY4f4x/+COwBoT4TwLbj9/T0tX33rCu6KkTMtTA6Dbl/rwyo14GyZcahnKSvAjWImBXM6QcfoPM9D0/9qbfuCsQU+237+zmmLd5FfSQOCWfe9g2bKMMYz04/EbnoloerFckikSSeamYp0ECckjD070NNgjFKfYgD6pYY4J6Bg6zTVwyDM0RsU3cHS/5f8SYukZKyIyqHWeBPrwqn/2L+vSFpIAew9wsrjGMM6D4YsGrXJqzCnbTcSLR301LvWQMA/AZw/BkjloXYIejhjJiFerxM5/SAQUk4pwskvhpX7KhuoQqwVsrZhYM5yb05r6+S3UIJT/QSgWTJvmZpq/cCyRQZQdnu/xnW2EBMvlDYGdsAx/NZJcbn+zDjV08kCWe8wcCx0P++pAxYLE7bIsJ2h4eZxaMpWxQlDdVQ+7m+PC9GiS6aFkxArpVg/cZGmDFUxvY0XG8zsnusIpZyMGCwsP093p3aH5PKeuZO+jeevsSl96zgBs0m4UyCCBEWa3RsgPQBrXhrqZSmS7Do9LkDWMWJJF4=}
